college Start
kamilnapiontek/college pull request #1
Opened 2023-04-17 14:33 UTC by kamilnapiontek

siemka wyskakuje mi błąd, wydaje mi się, że to przez fetch = FetchType.LAZY,
ale nie wiem czy wszystko robię zgodnie ze sztuką :P możesz rzucić okiem?
[blad.txt](https://github.com/kamilnapiontek/college/files/11251377/blad.txt)

2023-04-17 16:24 UTC, Y0ucandev commented
W takich przypadkach jak Twoje mapowanie musi byc FetchType.EAGER
ale lepiej napisz swoje query z JOIN FETCH 
https://medium.com/javarevisited/spring-jpa-when-to-use-join-fetch-a6cec898c4c6

2023-04-17 16:28 UTC, Y0ucandev requested changes

2023-04-17 16:28 UTC, Y0ucandev commented on .mvn/wrapper/maven-wrapper.properties
> +# Licensed to the Apache Software Foundation (ASF) under one
tego nie powinno byc w repo

2023-04-17 16:28 UTC, Y0ucandev commented on mvnw
> +# "License"); you may not use this file except in compliance
tego nie powinno byc w repo

2023-04-17 16:28 UTC, Y0ucandev commented on mvnw.cmd
> +@REM MAVEN_BATCH_PAUSE - set to 'on' to wait for a keystroke before ending
tego nie powinno byc w repo

2023-04-17 16:28 UTC, Y0ucandev commented on src/main/java/com/example/college/Address.java
> +
zbedna pusta linia

2023-04-17 16:28 UTC, Y0ucandev commented on src/main/java/com/example/college/College.java
> +        fetch = FetchType.LAZY
w takim mapowaniu EAGER tu 
albo lepiej join fetch bo crashuje appke

2023-04-17 16:28 UTC, Y0ucandev commented on src/main/java/com/example/college/CollegeRepository.java
> +
zbedna pusta linia

2023-04-17 16:28 UTC, Y0ucandev commented on src/main/java/com/example/college/CollegeService.java
> +        }, () -> System.err.println("Ni ma takiego w bazie"));
po angielsku te komentarze w wyjatkach. i na pewno nie sout ....

2023-04-17 16:28 UTC, Y0ucandev commented on src/main/java/com/example/college/CollegeService.java
> +        }, () -> System.err.println("Ni ma takiego w bazie"));
LOGGERA uzywaj

2023-04-17 16:28 UTC, Y0ucandev commented on src/main/resources/application.properties
> +
do wyrzucenia

2023-04-18 20:06 UTC, kamilnapiontek commented on src/main/java/com/example/college/CollegeService.java
> +        }, () -> System.err.println("Ni ma takiego w bazie"));
później podmienię, najpierw chciałbym, żeby działało :P

2023-04-18 20:10 UTC, kamilnapiontek commented on src/main/java/com/example/college/CollegeService.java
> +        }, () -> System.err.println("Ni ma takiego w bazie"));
Dalej nie działa, nie mam pojęcia czemu, zobaczymy na zajęciach
IdIdę się bawić ze streamamię się bawić ze streamami

2023-04-18 20:11 UTC, kamilnapiontek commented on src/main/java/com/example/college/CollegeService.java
> +        }, () -> System.err.println("Ni ma takiego w bazie"));
Dalej nie działa, nie mam pojęcia czemu, zobaczymy na zajęciach
Idę się bawić ze streamami

2023-04-19 08:35 UTC, Y0ucandev commented on src/main/java/com/example/college/CollegeService.java
> +        }, () -> System.err.println("Ni ma takiego w bazie"));
Lepiej pozno niz wcale

2023-04-20 23:07 UTC, Y0ucandev requested changes

2023-04-20 23:07 UTC, Y0ucandev commented on src/main/java/com/example/college/department/DepartmentRepository.java
> +package com.example.college.department;public interface DepartmentRepository {
co to ma byc ? i tak samo w X plikach nizej

2023-04-21 02:37 UTC, kamilnapiontek commented on src/main/java/com/example/college/department/DepartmentRepository.java
> +package com.example.college.department;public interface DepartmentRepository {
![image](https://user-images.githubusercontent.com/43855312/233527418-71477b05-af4f-4ed1-a9e6-e39ab1d23271.png)

2023-04-21 02:38 UTC, kamilnapiontek commented on src/main/java/com/example/college/department/DepartmentRepository.java
> +package com.example.college.department;public interface DepartmentRepository {
Nie rozumiem, u mnie wygląda w ten sposób

2023-04-21 21:23 UTC, Y0ucandev requested changes

2023-04-21 21:23 UTC, Y0ucandev commented on src/main/java/com/example/college/CollegeApplication.java
> +
po co tyle pustych linii ?

2023-04-21 21:23 UTC, Y0ucandev commented on src/main/java/com/example/college/department/DepartmentService.java
> +            throw new NoSuchElementException("Department not found");
wrzuc to w jedna linijke. Uzyj lambdy

2023-04-21 21:23 UTC, Y0ucandev commented on src/main/java/com/example/college/enums/AcademicTitle.java
> +    DOCTOR,
PhD to chyba doktor w USA, Doctor to lekarz

2023-04-21 21:23 UTC, Y0ucandev commented on src/main/java/com/example/college/lecturer/LecturerService.java
> +                new BigDecimal(3000), LocalDate.now(), true, AcademicTitle.DOCTOR);
Zrob jakas jedna klase UTIL ktora bedzie miala ten caly generowany smietnik. W serwisach nie ma na to miejsca. 
To tyczy sie tego miejsca i kazdego innego

2023-04-21 21:23 UTC, Y0ucandev commented on src/main/java/com/example/college/major/Major.java
> +    public String toString() {
moze by tak uzyc lomboka zamiast produkowac boilerplate code ? Po to on jest

2023-04-21 21:23 UTC, Y0ucandev commented on src/main/java/com/example/college/major/MajorService.java
> +    private void addSubject(Major major, String name) {
bym to raczej lepiej nazwal bo save tez tam sie odbywa jakis widze

2023-04-21 21:23 UTC, Y0ucandev commented on src/main/java/com/example/college/lecturer/Lecturer.java
> +    }
moze bys tak jakis wzorzec projektowy tu zastosowal?

2023-04-24 15:41 UTC, kamilnapiontek commented on src/main/java/com/example/college/lecturer/Lecturer.java
> +    }
w sensie builder?

2023-04-26 08:10 UTC, Y0ucandev approved these changes

2023-04-26 08:10 UTC, Y0ucandev commented on src/main/java/com/example/college/lecturer/Lecturer.java
> +    }
tak

2023-04-26 08:11 UTC, merged

2023-04-26 08:11 UTC, Y0ucandev commented on src/main/java/com/example/college/lecturer/Lecturer.java
> +    }
zrob dla niego nowego pra